name: Contract coverage
on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]
jobs:
    coverage:
        name: Contract coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build contracts
              run: yarn compile

            - name: Run coverage
              run: yarn coverage

            - name: Upload report
              run: bash <(curl -s https://codecov.io/bash)
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
